-- Account Service DDL (MSSQL)
-- Accounts table with rowversion for optimistic concurrency
CREATE TABLE Accounts (
    AccountId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
    CustomerId UNIQUEIDENTIFIER NOT NULL,
    AccountType NVARCHAR(50) NOT NULL,
    Currency NVARCHAR(3) NOT NULL,
    Balance DECIMAL(18,4) NOT NULL DEFAULT 0,
    Status NVARCHAR(50) NOT NULL DEFAULT 'Active',
    CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    UpdatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    RowVersion ROWVERSION
);

CREATE TABLE SubAccounts (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
    ParentAccountId UNIQUEIDENTIFIER NOT NULL REFERENCES Accounts(AccountId) ON DELETE CASCADE,
    Name NVARCHAR(200) NOT NULL,
    Balance DECIMAL(18,4) NOT NULL DEFAULT 0,
    CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
);

CREATE INDEX IX_Accounts_CustomerId ON Accounts(CustomerId);
